"""Generate the sqlfluff config that lets sqlfluff run alongside sqlalign.

The two tools overlap, and left to themselves they fight: `sqlfluff fix` would
undo the columnar alignment on every run. The resolution is the one Prettier and
`eslint-config-prettier` settled on years ago: **the formatter owns layout, and
the linter is told to stop having opinions about it**. sqlalign generates that
instruction rather than making a team hand-maintain it.

Two principles decide what goes in:

1. **Disable the whole `layout` GROUP, not a list of rules.** Naming individual
   rules dates instantly: a sqlfluff upgrade that adds a layout rule would start
   failing formatted output, and the config would need editing to catch up. The
   group covers rules that do not exist yet.

2. **Keep every semantic rule ON.** `ambiguous.column_references`,
   `aliasing.expression`, `convention.casting_style`,
   `structure.join_condition_order` and the rest lint the AUTHOR'S SQL, which is
   exactly what a linter is for. sqlalign preserves those choices rather than
   rewriting them, so there is no conflict to resolve, and silencing them would
   quietly narrow what the team's linter is allowed to notice.

   (The repository's own `.sqlfluff` DOES exclude three of them. That is a
   different file with a different job: it gates a fixture set that deliberately
   mixes styles. It is not what a user should run.)

Everything else here is a genuine collision, where sqlalign and sqlfluff both
have a defensible opinion and must be told to agree. Each is derived from the
user's effective `Style`, so a team that sets `keyword_case = "lower"` gets a
config that expects lowercase rather than one that immediately contradicts them.
"""
from sqlalign.style import Style

# The sqlfluff release this mapping was checked against. Stamped into the output
# so a future reader can tell whether the config predates their linter: rule
# names and config keys are versioned surface, and a silent mismatch reads as
# "sqlalign generated a broken config" rather than "these have drifted apart".
#
# Bumping it means re-running the coexistence tests against that release, which
# exercise every rule and config key below through the real linter.
TESTED_SQLFLUFF = "4.3.0"

# style knob -> (sqlfluff rule, config key, {style value: sqlfluff value})
_MAPPINGS = (
    # sqlalign prints `AS` on a table alias or omits it; sqlfluff's AL01 wants to
    # know which, and defaults to `explicit`, so the house default (bare) fails
    # a stock sqlfluff install on every joined query.
    ("table_alias_style", "aliasing.table", "aliasing",
     {"bare": "implicit", "as": "explicit"}),
    # Both spellings collapse at parse time, so sqlalign must pick one; CV01
    # defaults to `consistent`, which is satisfied either way, but stating it
    # means a hand-written statement that disagrees is reported.
    ("neq_style", "convention.not_equal", "preferred_not_equal_style",
     {"!=": "c_style", "<>": "ansi"}),
    ("keyword_case", "capitalisation.keywords", "capitalisation_policy",
     {"upper": "upper", "lower": "lower"}),
    ("keyword_case", "capitalisation.functions", "extended_capitalisation_policy",
     {"upper": "upper", "lower": "lower"}),
    ("keyword_case", "capitalisation.literals", "capitalisation_policy",
     {"upper": "upper", "lower": "lower"}),
    ("keyword_case", "capitalisation.types", "extended_capitalisation_policy",
     {"upper": "upper", "lower": "lower"}),
)


def sqlfluff_config(style: Style, dialect: str) -> str:
    """The `.sqlfluff` a team should use next to this `style`."""
    lines = [
        f"# Generated by sqlalign for sqlfluff {TESTED_SQLFLUFF}. Regenerate with:",
        "#     sqlalign --print-sqlfluff-config > .sqlfluff",
        "#",
        "# sqlalign owns layout, so the whole `layout` rule GROUP is excluded --",
        "# by group rather than by name, so a sqlfluff upgrade that adds a layout",
        "# rule cannot start failing formatted output.",
        "#",
        "# Every semantic rule stays ON. Those lint your SQL, not sqlalign's",
        "# whitespace, and sqlalign preserves the choices they are about.",
        "[sqlfluff]",
        f"dialect = {dialect}",
        "exclude_rules = layout",
        # Line length lives in the layout group and is therefore already off;
        # stating it keeps the file honest if someone narrows exclude_rules.
        "max_line_length = -1",
    ]
    for knob, rule, key, table in _MAPPINGS:
        value = table.get(getattr(style, knob))
        if value is None:                      # a knob value with no sqlfluff analogue
            continue
        lines += ["", f"# from sqlalign's {knob}", f"[sqlfluff:rules:{rule}]",
                  f"{key} = {value}"]
    return "\n".join(lines) + "\n"
