"""The built documentation site.

`docs/v1/` is GENERATED by `tools/build_docs.py` and COMMITTED, because GitHub
Pages runs no build step — the HTML in the repository is what ships. That makes
the build output a source artefact like any other, and these tests are what stop
it going stale or breaking silently.

The one that matters most is `test_the_committed_site_matches_the_generator`:
edit the guide markdown, or a setting, or the formatter itself, and the site is
out of date until someone reruns the build. Nothing else would notice.
"""
import html
import pathlib
import re
import subprocess
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = ROOT / "docs" / "v1"
PAGES = sorted(SITE.glob("*.html"))


def _body(page: pathlib.Path) -> str:
    """The page with its <script> stripped — JS string literals are not links."""
    return re.sub(r"<script>.*?</script>", "", page.read_text(), flags=re.S)


def test_the_site_was_built():
    assert PAGES, "docs/v1 is empty; run `uv run python tools/build_docs.py`"
    assert (SITE / "search-index.json").exists()


@pytest.mark.parametrize("page", PAGES, ids=lambda p: p.name)
def test_every_page_has_its_chrome(page):
    text = page.read_text()
    for needed in ('<meta charset="utf-8">', 'class="side"', 'id="q"',
                   'class="version"', 'id="theme"', 'id="main"'):
        assert needed in text, f"{page.name} is missing {needed}"


@pytest.mark.parametrize("page", PAGES, ids=lambda p: p.name)
def test_no_broken_internal_links(page):
    for href in re.findall(r'href="([^"#][^"]*)"', _body(page)):
        if href.startswith(("http", "mailto:")):
            continue
        assert (page.parent / href.split("#")[0]).resolve().exists(), (
            f"{page.name} links to {href}, which does not exist")


@pytest.mark.parametrize("page", PAGES, ids=lambda p: p.name)
def test_no_dead_anchors(page):
    known = {p.name: set(re.findall(r'\bid="([^"]+)"', p.read_text())) for p in PAGES}
    for href in re.findall(r'href="([^"]*#[^"]+)"', _body(page)):
        if href.startswith("http"):
            continue
        target, _, frag = href.partition("#")
        name = target or page.name
        if name in known:
            assert frag in known[name], f"{page.name} links to a missing #{frag}"


@pytest.mark.parametrize("page", PAGES, ids=lambda p: p.name)
def test_ids_are_unique(page):
    ids = re.findall(r'\bid="([^"]+)"', page.read_text())
    duplicates = {i for i in ids if ids.count(i) > 1}
    assert not duplicates, f"{page.name} repeats {duplicates}"


@pytest.mark.parametrize("page", PAGES, ids=lambda p: p.name)
def test_no_unrendered_markdown_leaked_through(page):
    """A `backtick` that survives into the HTML means some string was escaped
    instead of rendered — which is how the setting summaries first shipped."""
    text = re.sub(r"<(pre|code)[^>]*>.*?</\1>", "", _body(page), flags=re.S)
    assert "`" not in text, f"{page.name} has a literal backtick outside code"
    assert "](" not in text, f"{page.name} has an unrendered markdown link"


# ---- the settings reference ----------------------------------------------

def test_every_style_field_is_documented():
    """The load-bearing one: add a knob to `Style` and this fails until the
    reference documents it. A setting nobody can find is a setting nobody has."""
    import dataclasses

    sys.path.insert(0, str(ROOT / "tools"))
    from docs_settings import SETTINGS

    from sqlalign.style import Style

    documented = {s.name for s in SETTINGS}
    fields = {f.name for f in dataclasses.fields(Style)}
    assert fields - documented == set(), f"undocumented settings: {fields - documented}"
    assert documented - fields == set(), f"documented but gone: {documented - fields}"


def test_every_setting_example_is_generated_from_a_real_run():
    """Each panel must be what the formatter actually produces for that value.

    Not a style check — a correctness one. A hand-written example is a claim
    about the tool that nothing verifies; this asserts the page and the engine
    cannot disagree.
    """
    sys.path.insert(0, str(ROOT / "tools"))
    from docs_settings import SETTINGS, style_for

    from sqlalign.formatter import format_sql

    page = (SITE / "settings.html").read_text()
    for setting in SETTINGS:
        for value in setting.values:
            result = format_sql(setting.sample, "postgres", style_for(setting, value))
            expected = html.escape(result.text if not result.warnings
                                   else result.text.strip())
            assert expected in page, (
                f"{setting.name} with {value!r}: the page does not show what the "
                f"formatter produces")


def test_each_setting_shows_values_that_actually_differ():
    """Two identical panels teach nothing. Every documented value must render
    differently from the others, or the sample does not exercise the knob."""
    sys.path.insert(0, str(ROOT / "tools"))
    from docs_settings import SETTINGS, style_for

    from sqlalign.formatter import format_sql

    for setting in SETTINGS:
        seen = set()
        for value in setting.values:
            result = format_sql(setting.sample, "postgres", style_for(setting, value))
            seen.add("DECLINED" if result.warnings else result.text)
        assert len(seen) == len(setting.values), (
            f"{setting.name}: its sample does not distinguish all of "
            f"{[str(v) for v in setting.values]}")


def test_the_search_index_covers_every_page():
    import json

    index = json.loads((SITE / "search-index.json").read_text())
    assert {d["slug"] for d in index} == {p.stem for p in PAGES}
    settings = next(d for d in index if d["slug"] == "settings")
    assert any(h["id"] == "river_gutter" for h in settings["headings"]), (
        "settings are not individually findable")


# ---- the site is in sync with its generator -------------------------------

def test_the_committed_site_matches_the_generator():
    """Rebuild into a scratch directory and compare. This is what catches a
    guide edit, a settings change, or a formatter change that nobody rebuilt
    for — the site is committed, so nothing else would."""
    import shutil
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        scratch = pathlib.Path(tmp)
        shutil.copytree(ROOT / "docs" / "guide", scratch / "docs" / "guide")
        shutil.copytree(ROOT / "tools", scratch / "tools")
        (scratch / "src").symlink_to(ROOT / "src")
        proc = subprocess.run(
            [sys.executable, str(scratch / "tools" / "build_docs.py")],
            capture_output=True, text=True, cwd=scratch)
        assert proc.returncode == 0, proc.stderr

        built = scratch / "docs" / "v1"
        for page in PAGES:
            fresh = (built / page.name).read_text()
            assert fresh == page.read_text(), (
                f"docs/v1/{page.name} is stale — rerun "
                f"`uv run python tools/build_docs.py` and commit the result")


def test_every_flag_appears_in_the_cli_reference():
    """A reference page missing a third of the flags is not a reference.

    Generated from the parser rather than maintained by hand, so it cannot fall
    behind it again. The hand-written sections below the table explain the flags
    that need more than a line.
    """
    from sqlalign.cli import build_parser

    page = (SITE / "cli.html").read_text()
    flags = [opt for action in build_parser()._actions for opt in action.option_strings]
    assert len(flags) > 30, "the parser lost most of its flags"
    missing = [f for f in flags if f not in page]
    assert not missing, f"undocumented flags: {missing}"


def test_every_documented_choice_list_matches_the_parser():
    """A hand-written `{a,b,c}` in the prose is a claim about the parser that
    nothing else checks: the generated table renders choices its own way, and
    `test_every_flag_appears_in_the_cli_reference` only looks at flag names.
    `--preset` gained `gitlab` and `river` and its hand-written list did not.
    """
    import re

    from sqlalign.cli import build_parser

    real = {opt: list(action.choices)
            for action in build_parser()._actions if action.choices
            for opt in action.option_strings}

    stale = []
    for md in [*sorted((ROOT / "docs" / "guide").glob("*.md")), ROOT / "README.md"]:
        for match in re.finditer(r"(--[a-z][a-z0-9-]+) \{([^}]*)\}", md.read_text()):
            flag, listed = match.group(1), match.group(2).split(",")
            if real.get(flag) != listed:
                stale.append(f"{md.name}: {flag} documents {listed}, "
                             f"the parser has {real.get(flag)}")
    assert not stale, stale


def test_no_doc_example_runs_report_as_if_it_were_read_only():
    """`--report` and `--max-declines` add output without changing the mode, so
    on their own they rewrite the files they counted.

    The dialects guide told readers to run `sqlalign --report` over their own
    SQL to see what declined — following it would have reformatted the
    repository they were only trying to survey.
    """
    offenders = []
    for md in [*sorted((ROOT / "docs" / "guide").glob("*.md")), ROOT / "README.md"]:
        for number, line in enumerate(md.read_text().splitlines(), 1):
            if "sqlalign --report" not in line and "sqlalign --max-declines" not in line:
                continue
            if not any(mode in line for mode in ("--check", "--stdout", "--diff")):
                offenders.append(f"{md.name}:{number}: {line.strip()}")
    assert not offenders, (
        "these would rewrite the reader's files; pair with --check: " + str(offenders))


def test_every_flag_has_help_text():
    """`--help` is the reference most people read, and the page is generated
    from it — a flag with no help is blank in both."""
    from sqlalign.cli import build_parser

    bare = [action.option_strings[0] for action in build_parser()._actions
            if action.option_strings and not action.help]
    assert not bare, f"flags with no help text: {bare}"
