"""Build the documentation site into `docs/<version>/`.

    uv run python tools/build_docs.py

The site is GENERATED and COMMITTED. There is no CI and GitHub Pages runs no
build step, so the HTML in the repository is what ships -- which also means the
generator has to be run and its output reviewed like any other change.

Three things are derived rather than written:

  - the page bodies, from `docs/guide/*.md`, so prose is authored in markdown
  - every configuration example, by RUNNING the formatter under each value of
    each setting (tools/docs_settings.py). A hand-written example is a claim
    about the tool; a generated one is the tool.
  - the search index, from the rendered headings and text

Versioning is a directory. `docs/v1/` is the only version today; the selector
reads `VERSIONS` below, and adding one means building into a new directory and
leaving the old one alone. Nothing in a built page points outside its own
version, so an old version keeps working untouched.
"""
from __future__ import annotations

import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "tools"))

from docs_settings import SETTINGS, field_type, label, style_for  # noqa: E402
from markdown_it import MarkdownIt  # noqa: E402

from sqlalign.formatter import format_sql  # noqa: E402
from sqlalign.style import PRESETS, preset_style  # noqa: E402

REPO = "https://github.com/pua2/sqlalign"
VERSION = "v1"
VERSIONS = [("v1", "1.0 (current)")]

# (slug, source markdown, nav title, one-line blurb for the docs index)
PAGES = [
    ("index", None, "Overview",
     "What sqlalign is, what it guarantees, and where to go next."),
    ("getting-started", "getting-started.md", "Getting started",
     "Install it, run it on a file, wire it into a pre-commit hook."),
    ("configuration", "configuration.md", "Configuration",
     "The config file, the CLI flags that override it, and the presets."),
    ("settings", None, "Settings reference",
     "Every setting, with its default and the same SQL rendered under each value."),
    ("style", "style.md", "The house style",
     "What the output looks like, and the rule behind each decision."),
    ("cli", "cli.md", "CLI reference",
     "Every flag, its default, and what it does."),
    ("dialects", "dialects.md", "Dialects",
     "Postgres, Redshift and T-SQL — what each supports and what each declines."),
    ("architecture", "architecture.md", "Architecture",
     "The layout IR, the alignment resolver, and the safety model."),
    ("faq", "faq.md", "FAQ",
     "Why it declines, why it will not fix your SQL, and how it compares."),
]

MD = MarkdownIt("commonmark", {"html": True}).enable("table").enable("strikethrough")


def inline(text: str) -> str:
    """Render one line of markdown WITHOUT wrapping it in a paragraph -- summaries
    and captions carry `code` spans and sit inside their own elements."""
    return MD.renderInline(text)


# ---- rendering helpers ----------------------------------------------------

def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def anchored(body: str) -> tuple[str, list[tuple[int, str, str]]]:
    """Give every h2/h3 an id and a self-link; return the body and its outline."""
    outline: list[tuple[int, str, str]] = []

    def repl(m):
        level, text = int(m.group(1)), m.group(2)
        plain = re.sub(r"<[^>]+>", "", text)
        slug = slugify(plain)
        outline.append((level, slug, plain))
        return (f'<h{level} id="{slug}">{text}'
                f'<a class="anchor" href="#{slug}" aria-label="Link to this section">#</a>'
                f"</h{level}>")

    return re.sub(r"<h([23])>(.*?)</h\1>", repl, body, flags=re.S), outline


def sql_block(text: str) -> str:
    return f'<pre class="sql"><code>{html.escape(text)}</code></pre>'


# ---- the settings reference (generated by running the formatter) ----------

def settings_page() -> tuple[str, list[tuple[int, str, str]]]:
    parts = ["""<p class="lede">Every setting sqlalign has, with its type, its
default, and the <strong>same SQL rendered under each value</strong>. The
examples on this page are produced by running the formatter when the page is
built — none of them is written by hand, so none of them can drift away from
what the tool actually does.</p>

<p>Settings go in a <code>.sqlalign.toml</code> file under
<code>[tool.sqlalign]</code>, and most have a CLI flag that overrides the file
for one run. See <a href="configuration.html">Configuration</a> for how the two
combine, and <a href="cli.html">CLI reference</a> for the flags.</p>"""]
    outline: list[tuple[int, str, str]] = []

    parts.append('<div class="settings-index"><h2 id="all-settings">All settings'
                 '<a class="anchor" href="#all-settings">#</a></h2><ul>')
    outline.append((2, "all-settings", "All settings"))
    for s in SETTINGS:
        parts.append(f'<li><a href="#{s.name}"><code>{s.name}</code></a>'
                     f"<span>{inline(s.summary)}</span></li>")
    parts.append("</ul></div>")

    for s in SETTINGS:
        outline.append((3, s.name, s.name))
        default = label(s, s.values[0])
        parts.append(f"""<section class="setting" id="{s.name}">
<h3><code>{s.name}</code>
<a class="anchor" href="#{s.name}" aria-label="Link to this setting">#</a></h3>
<p class="summary">{inline(s.summary)}</p>
<dl class="meta">
  <div><dt>Type</dt><dd><code>{field_type(s.name)}</code></dd></div>
  <div><dt>Default</dt><dd><code>{html.escape(default)}</code></dd></div>
</dl>
<div class="detail">{MD.render(s.detail)}</div>""")
        if s.note:
            parts.append(f'<div class="note">{MD.render(s.note)}</div>')

        parts.append(f"<p class=\"sample-label\">Given this input:</p>{sql_block(s.sample)}")
        parts.append('<div class="panels">')
        for i, value in enumerate(s.values):
            result = format_sql(s.sample, "postgres", style_for(s, value))
            tag = " · default" if i == 0 else ""
            if result.warnings:
                body = ('<p class="declined">Declined — passed through unchanged.<br>'
                        f"<span>{html.escape(result.declines[0].reason)}</span></p>"
                        + sql_block(result.text.strip()))
            else:
                body = sql_block(result.text)
            parts.append(f'<figure><figcaption><code>{html.escape(label(s, value))}'
                         f"</code>{tag}</figcaption>{body}</figure>")
        parts.append("</div></section>")

    parts.append('<h2 id="presets">Presets<a class="anchor" href="#presets">#</a></h2>')
    outline.append((2, "presets", "Presets"))
    parts.append("<p>A preset is a named bundle of the settings above. "
                 "<code>--preset NAME</code> applies one, and any explicit setting "
                 "still wins over it.</p>")
    sample = SETTINGS[3].sample
    parts.append(f'<p class="sample-label">Given this input:</p>{sql_block(sample)}')
    parts.append('<div class="panels">')
    for name in sorted(PRESETS):
        out = format_sql(sample, "postgres", preset_style(name)).text
        parts.append(f'<figure><figcaption><code>{name}</code></figcaption>'
                     f"{sql_block(out)}</figure>")
    parts.append("</div>")
    return "\n".join(parts), outline


def flag_table() -> str:
    """Every flag, from argparse itself.

    Generated for the same reason the settings examples are: a hand-maintained
    list of flags falls behind the parser, and this one had drifted by twelve.
    """
    from sqlalign.cli import build_parser

    parser = build_parser()
    rows = []
    for action in parser._actions:
        if not action.option_strings:
            continue
        names = ", ".join(f"<code>{o}</code>" for o in action.option_strings)
        choices = ""
        if action.choices:
            choices = " " + ", ".join(f"<code>{c}</code>" for c in action.choices)
        # argparse help is written with markdown code spans; render them so a
        # backtick does not reach the page.
        help_text = inline(action.help or "")
        rows.append(f"<tr><td>{names}{choices}</td><td>{help_text}</td></tr>")
    return ('<h2 id="all-flags">All flags<a class="anchor" href="#all-flags">#</a></h2>'
            "<p>Generated from the parser, so it cannot fall behind it. The sections "
            "below explain the ones that need more than a line.</p>"
            "<table><thead><tr><th>Flag</th><th>Description</th></tr></thead><tbody>"
            + "".join(rows) + "</tbody></table>")


def overview_page() -> tuple[str, list[tuple[int, str, str]]]:
    demo = ("select cust.customer_id, cust.email, sum(ord.total) as lifetime_value "
            "from customers cust inner join orders ord on ord.customer_id = cust.customer_id "
            "where ord.order_date >= '2026-07-01' group by cust.customer_id, cust.email;")
    formatted = format_sql(demo, "postgres").text
    cards = "\n".join(
        f'<a class="card" href="{slug}.html"><h3>{html.escape(title)}</h3>'
        f"<p>{html.escape(blurb)}</p></a>"
        for slug, _src, title, blurb in PAGES if slug != "index")
    body = f"""<p class="lede">sqlalign is a SQL formatter that produces columnar,
aligned output — and re-parses every statement it writes to prove it did not
change what the SQL means.</p>

<p class="sample-label">In:</p>{sql_block(demo)}
<p class="sample-label">Out:</p>{sql_block(formatted)}

<h2 id="the-guarantee">The guarantee<a class="anchor" href="#the-guarantee">#</a></h2>
<p>Every statement is re-parsed after formatting and compared against the input
as a syntax tree. If the output would differ semantically — or if the engine
does not fully model the construct — that statement is passed through
byte-identical with a warning instead. A passthrough is not a failure, and the
run still exits <code>0</code>.</p>

<h2 id="pages">Pages<a class="anchor" href="#pages">#</a></h2>
<div class="cards">{cards}</div>"""
    return body, [(2, "the-guarantee", "The guarantee"), (2, "pages", "Pages")]


# ---- page chrome ----------------------------------------------------------

def shell(slug: str, title: str, body: str, outline, css: str, js: str) -> str:
    nav = "\n".join(
        f'<a href="{s}.html"{" class=\'here\'" if s == slug else ""}>{html.escape(t)}</a>'
        for s, _src, t, _b in PAGES)
    toc = "".join(
        f'<a class="lvl{lvl}" href="#{sl}">{html.escape(tx)}</a>'
        for lvl, sl, tx in outline) or ""
    toc_block = '<p class="side-h">On this page</p>' + toc if toc else ""
    versions = "".join(
        f'<option value="{v}"{" selected" if v == VERSION else ""}>{html.escape(lab)}</option>'
        for v, lab in VERSIONS)
    return f"""<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)} — sqlalign docs</title>
<meta name="description" content="{html.escape(title)} — sqlalign, a SQL
formatter that cannot change what your SQL means.">
<style>{css}</style>
<a class="skip" href="#main">Skip to content</a>
<header class="top">
  <a class="brand" href="../index.html">sqlalign</a>
  <select class="version" aria-label="Documentation version">{versions}</select>
  <div class="search">
    <input id="q" type="search" placeholder="Search docs…" autocomplete="off"
           aria-label="Search documentation">
    <div id="results" role="listbox" hidden></div>
  </div>
  <a class="ext" href="{REPO}">GitHub</a>
  <button id="theme" aria-label="Toggle colour scheme">◐</button>
</header>
<div class="shell">
  <nav class="side" aria-label="Documentation sections">
    <p class="side-h">Documentation</p>{nav}</nav>
  <main id="main">{body}</main>
  <aside class="toc" aria-label="On this page">{toc_block}</aside>
</div>
<script>{js}</script>
"""


def build() -> None:
    out = ROOT / "docs" / VERSION
    out.mkdir(parents=True, exist_ok=True)
    css = (ROOT / "tools" / "docs.css").read_text()
    js = (ROOT / "tools" / "docs.js").read_text()
    guide = ROOT / "docs" / "guide"

    index: list[dict] = []
    for slug, source, title, _blurb in PAGES:
        if slug == "settings":
            body, outline = settings_page()
        elif slug == "index":
            body, outline = overview_page()
        else:
            raw = (guide / source).read_text()
            # Drop the markdown H1; the page title carries it.
            raw = re.sub(r"\A#\s+.*?\n", "", raw, count=1)
            # Point cross-links at the built pages -- including the ones that
            # carry an anchor, which an earlier version of this regex missed and
            # which then 404'd.
            raw = re.sub(r"\]\((\w[\w-]*)\.md(#[\w-]*)?\)",
                         lambda m: f"]({m.group(1)}.html{m.group(2) or ''})", raw)
            raw = raw.replace("](README.html)", "](index.html)")
            # The repository README is not part of the published site, so a
            # relative link to it 404s on Pages. Send readers to GitHub.
            raw = raw.replace("](../../README.md)", f"]({REPO}/blob/main/README.md)")
            body, outline = anchored(MD.render(raw))
            if slug == "cli":
                body = flag_table() + body
                outline.insert(0, (2, "all-flags", "All flags"))
        (out / f"{slug}.html").write_text(shell(slug, title, body, outline, css, js))
        text = re.sub(r"<[^>]+>", " ", body)
        index.append({"slug": slug, "title": title,
                      "text": re.sub(r"\s+", " ", html.unescape(text))[:24000],
                      "headings": [{"id": sl, "text": tx} for _l, sl, tx in outline]})
    (out / "search-index.json").write_text(json.dumps(index, separators=(",", ":")))
    print(f"built {len(PAGES)} pages -> docs/{VERSION}/")
    for slug, *_ in PAGES:
        print(f"  {slug}.html")


if __name__ == "__main__":
    build()
