"""The per-setting reference data, and the SQL that demonstrates each one.

Every example on the configuration page is GENERATED by running the formatter,
never written by hand -- the same rule the guide's console transcripts follow.
A hand-written example is a claim about the tool; a generated one is the tool.

Each entry carries the SQL that actually exercises its knob. A shared sample
would leave most settings showing two identical panels: `on_placement` needs a
join, `river_gutter` needs a river, `body_blank_lines` needs a `$$` body. The
sample is the part that cannot be derived, so it is the part written down here.
"""
from __future__ import annotations

import dataclasses

from sqlalign.config import Width
from sqlalign.style import ALL_ALIGN_TARGETS, HOUSE, SETTING_SUMMARIES, Style

JOIN = ("select cust.id, cust.email, ord.total from customers cust "
        "inner join orders ord on ord.customer_id = cust.id "
        "where ord.total > 0 and cust.segment = 'enterprise';")

LIST = "select customer_id, email, signup_date from customers where active;"

ALIASED = ("select cust.id as customer, sum(ord.total) as lifetime_value "
           "from customers cust join orders ord on ord.customer_id = cust.id "
           "group by cust.id;")

BODY = ("create function bump() returns int as $$ begin update t set n = n + 1; "
        "return 1; end; $$ language plpgsql;")

TWO = "select a from t;\nupdate u set b = 2 where c = 3;"

WIDE = ("select customer_id, coalesce(sum(case when status = 'paid' "
        "then amount end), 0.00) as paid_total from ledger group by customer_id;")


@dataclasses.dataclass(frozen=True)
class Setting:
    name: str
    summary: str
    detail: str
    values: tuple            # the values to render, default first
    sample: str
    kind: str = "choice"     # choice | flag | number | targets
    note: str = ""


SETTINGS: tuple[Setting, ...] = (
    Setting(
        name="keyword_case",
        summary=SETTING_SUMMARIES["keyword_case"],
        detail="Applies to keywords and function names, never to identifiers or "
               "string literals — a quoted identifier keeps the spelling you gave "
               "it, because in most dialects that spelling is load-bearing.",
        values=("upper", "lower"),
        sample=LIST,
    ),
    Setting(
        name="align",
        summary=SETTING_SUMMARIES["align"],
        detail="With it off, every alignment column collapses to a single space "
               "and you get the same line structure without the padding — which "
               "is what nine of ten published style guides ask for. Nothing else "
               "about the layout changes, so turning it off is not a different "
               "style so much as the same style unpadded.",
        values=(True, False),
        sample=JOIN,
        kind="flag",
    ),
    Setting(
        name="align_targets",
        summary=SETTING_SUMMARIES["align_targets"],
        detail="A set of names. `aliases` is shorthand for `column_aliases` plus "
               "`table_aliases`. Anything not listed simply takes one space, so "
               "you can keep the join-condition column and drop the rest.",
        values=(HOUSE.align_targets, frozenset({"operators"}), frozenset()),
        sample=JOIN,
        kind="targets",
        note="Available: " + ", ".join(f"`{t}`" for t in sorted(ALL_ALIGN_TARGETS)),
    ),
    Setting(
        name="comma_position",
        summary=SETTING_SUMMARIES["comma_position"],
        detail="Leading commas put the separator where the eye already is when "
               "scanning a column of items, and make adding or removing the last "
               "item a one-line diff.",
        values=("leading", "trailing"),
        sample=LIST,
    ),
    Setting(
        name="boolean_operator_position",
        summary=SETTING_SUMMARIES["boolean_operator_position"],
        detail="The same choice as `comma_position`, for predicates. Leading "
               "operators right-align under the clause keyword, so `WHERE`, `AND` "
               "and `OR` all end in the same column.",
        values=("leading", "trailing"),
        sample=JOIN,
    ),
    Setting(
        name="on_placement",
        summary=SETTING_SUMMARIES["on_placement"],
        detail="Inline keeps a join to one row and lets the `ON` column align "
               "across the whole FROM block. On its own line it drops below, "
               "indented, which reads better when conditions are long.",
        values=("inline", "own_line"),
        sample=JOIN,
    ),
    Setting(
        name="select_placement",
        summary=SETTING_SUMMARIES["select_placement"],
        detail="Inline starts the list on the `SELECT` row itself. `own_line` "
               "puts every item below, indented by `select_indent` — the dbt and "
               "GitLab convention.",
        values=("inline", "own_line"),
        sample=LIST,
    ),
    Setting(
        name="select_indent",
        summary=SETTING_SUMMARIES["select_indent"],
        detail="Only applies when `select_placement` is `own_line`; it is greyed "
               "out in the GUI otherwise, and ignored here.",
        values=(2, 4),
        sample=LIST,
        kind="number",
        note="Rendered below with `select_placement = own_line`, since the "
             "setting does nothing without it.",
    ),
    Setting(
        name="clause_keyword_align",
        summary=SETTING_SUMMARIES["clause_keyword_align"],
        detail="A river right-aligns every root keyword so its last character "
               "lands on a shared gutter, which puts every clause body in one "
               "column. It is the arrangement Holywell's style guide describes.",
        values=("left", "river"),
        sample=JOIN,
    ),
    Setting(
        name="river_gutter",
        summary=SETTING_SUMMARIES["river_gutter"],
        detail="The column every root keyword ends on. Fixed rather than derived "
               "from the widest keyword present, so a clause added later cannot "
               "shift the whole statement sideways.",
        values=(6, 10),
        sample=JOIN,
        kind="number",
        note="Rendered below with `clause_keyword_align = river`, since the "
             "setting does nothing without it.",
    ),
    Setting(
        name="table_alias_style",
        summary=SETTING_SUMMARIES["table_alias_style"],
        detail="`FROM orders ord` and `FROM orders AS ord` parse identically, so "
               "which one comes out is sqlalign's decision rather than yours — "
               "which is exactly why it is a setting.",
        values=("bare", "as"),
        sample=ALIASED,
    ),
    Setting(
        name="neq_style",
        summary=SETTING_SUMMARIES["neq_style"],
        detail="`<>` and `!=` parse to the same node, so the distinction is lost "
               "before layout ever runs and one of them has to be chosen. Set it "
               "to whatever your linter expects.",
        values=("!=", "<>"),
        sample="select a from t where status != 'draft' and total <> 0;",
    ),
    Setting(
        name="decimal_style",
        summary=SETTING_SUMMARIES["decimal_style"],
        detail="`DECIMAL` and `NUMERIC` are synonyms that parse to one node — the "
               "same forced choice as `neq_style`.",
        values=("NUMERIC", "DECIMAL"),
        sample="create table t (amount decimal(10, 2), rate numeric(5, 4));",
    ),
    Setting(
        name="width",
        summary=SETTING_SUMMARIES["width"],
        detail="A trigger for the breaks that are modelled, not a hard ceiling: "
               "an expression with no modelled break stays on one line however "
               "long it is. `0` turns the limit off entirely.",
        values=(Width(100), Width(60)),
        sample=WIDE,
        kind="number",
        note="`0` turns the limit off, which is the same as a width nothing "
             "reaches — so it is described here rather than shown.",
    ),
    Setting(
        name="blank_lines_between_statements",
        summary=SETTING_SUMMARIES["blank_lines_between_statements"],
        detail="Unset, the house rule applies: exactly one blank line between two "
               "statements when both are multi-line, and otherwise whatever "
               "adjacency the input had. A number overrides that for every pair.",
        values=(None, 0, 2),
        sample=TWO,
        kind="number",
    ),
    Setting(
        name="body_blank_lines",
        summary=SETTING_SUMMARIES["body_blank_lines"],
        detail="A procedure body has its own vertical rhythm, separate from the "
               "one between top-level statements.",
        values=(1, 0),
        sample=BODY,
        kind="number",
    ),
    Setting(
        name="format_dollar_bodies",
        summary=SETTING_SUMMARIES["format_dollar_bodies"],
        detail="With it off the whole `CREATE FUNCTION` is left byte-identical. "
               "Useful for staging a migration: format the repository, leave the "
               "procedures for a later pass.",
        values=(True, False),
        sample=BODY,
        kind="flag",
    ),
    Setting(
        name="protect_templating",
        summary=SETTING_SUMMARIES["protect_templating"],
        detail="`{{ ref('x') }}` is not SQL and sqlglot cannot parse it. With this "
               "on, each template expression is replaced by a placeholder for the "
               "duration of the parse and restored afterwards, so a dbt model "
               "formats instead of declining.",
        values=(True, False),
        sample="select * from {{ ref('stg_orders') }} where status = 'paid';",
        kind="flag",
    ),
)


def style_for(setting: Setting, value):
    """HOUSE with `setting` set to `value`, plus whatever else the setting needs
    to have any visible effect."""
    overrides = {setting.name: value}
    if setting.name == "select_indent":
        overrides["select_placement"] = "own_line"
    if setting.name == "river_gutter":
        overrides["clause_keyword_align"] = "river"
    return dataclasses.replace(HOUSE, **overrides)


def label(setting: Setting, value) -> str:
    """How a value is written in the docs."""
    if setting.kind == "targets":
        if not value:
            return "frozenset()"
        if value == HOUSE.align_targets:
            return "the default set"
        return "{" + ", ".join(sorted(value)) + "}"
    if isinstance(value, Width):
        return f"{value.width}" if value.width else "0 (off)"
    return repr(value)


def field_type(name: str) -> str:
    for f in dataclasses.fields(Style):
        if f.name == name:
            t = f.type if isinstance(f.type, str) else getattr(f.type, "__name__", str(f.type))
            return {"bool": "bool", "int": "int", "str": "str",
                    "frozenset[str]": "set of str",
                    "int | None": "int or unset"}.get(t, t)
    raise KeyError(name)
