"""Download the third-party SQL that `tests/test_corpus.py` runs over.

The corpus is VENDORED rather than fetched at test time. A test suite that
clones repositories is one where a red build might mean GitHub was slow, and the
whole point of the corpus is that a failure means sqlalign broke.

Every source is pinned to a commit. Re-running this without changing the pins
produces the same bytes; changing a pin is a deliberate commit with a reason,
the same way a golden changes.

    uv run python tools/fetch_corpus.py

Attribution and licences are written to tests/corpus/README.md, generated from
SOURCES so the two cannot disagree.
"""
from __future__ import annotations

import json
import pathlib
import shutil
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
CORPUS = ROOT / "tests" / "corpus"


class Source:
    def __init__(self, name, repo, commit, licence, why, paths=None, tree=None, limit=None):
        self.name = name
        self.repo = repo
        self.commit = commit
        self.licence = licence
        self.why = why
        self.paths = paths or []
        self.tree = tree          # directory prefix to take everything under
        self.limit = limit


SOURCES = [
    Source(
        name="sqlglot",
        repo="tobymao/sqlglot",
        commit="29c651b85309693924b8c034501e6a2733d14588",   # v30.14.0
        licence="MIT",
        why=("The parser's own fixtures, pinned to the version sqlalign depends on. "
             "One statement per line and deliberately adversarial: it is the SQL "
             "sqlglot's authors thought worth testing a parser against."),
        paths=["tests/fixtures/identity.sql",
               "tests/fixtures/pretty.sql",
               "tests/fixtures/optimizer/optimizer.sql"],
    ),
    Source(
        name="jaffle-shop",
        repo="dbt-labs/jaffle-shop-classic",
        commit="fd7bfacae4f497ff044a6a0275268676bf1b64c3",
        licence="Apache-2.0",
        why=("dbt's canonical example project. Small, but it is the shape of SQL "
             "the target audience actually writes and the first thing many teams "
             "would run sqlalign over."),
        tree="models/",
    ),
    Source(
        name="dbt-expectations",
        repo="calogica/dbt-expectations",
        commit="db3dc81dada4bf987a3beee375978421568a240a",
        licence="Apache-2.0",
        why=("Heavy Jinja: macros with control flow, nested calls and templated "
             "identifiers. This is what exercises the templating mask, which is "
             "the part of the pipeline most likely to mangle real dbt code."),
        tree="macros/",
        limit=40,
    ),
]


def _get(url: str) -> bytes:
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read()


def _paths_for(source: Source) -> list[str]:
    if source.paths:
        return source.paths
    listing = json.loads(_get(
        f"https://api.github.com/repos/{source.repo}/git/trees/{source.commit}?recursive=1"))
    found = sorted(entry["path"] for entry in listing["tree"]
                   if entry["path"].startswith(source.tree)
                   and entry["path"].endswith(".sql"))
    return found[:source.limit] if source.limit else found


def main() -> None:
    if CORPUS.exists():
        shutil.rmtree(CORPUS)
    CORPUS.mkdir(parents=True)

    counts = {}
    for source in SOURCES:
        target = CORPUS / source.name
        target.mkdir()
        paths = _paths_for(source)
        for path in paths:
            raw = _get(f"https://raw.githubusercontent.com/"
                       f"{source.repo}/{source.commit}/{path}")
            # Flattened: the corpus is read as a bag of SQL, and nested paths
            # only make the directory harder to look through.
            (target / path.replace("/", "__")).write_bytes(raw)
        counts[source.name] = len(paths)
        print(f"  {source.name}: {len(paths)} files")

    (CORPUS / "README.md").write_text(_readme(counts))
    print(f"  wrote {CORPUS / 'README.md'}")


def _readme(counts: dict[str, int]) -> str:
    lines = [
        "# Corpus",
        "",
        "Third-party SQL that `tests/test_corpus.py` runs the formatter over.",
        "**Generated by `tools/fetch_corpus.py` — do not edit by hand.**",
        "",
        "None of this SQL was written for sqlalign, which is the point: fixtures",
        "written alongside a formatter test what its author already thought of.",
        "",
        "Every source is pinned to a commit, and the files are committed rather",
        "than fetched at test time — a suite that clones repositories is one where",
        "a red build might mean GitHub was slow.",
        "",
    ]
    for source in SOURCES:
        lines += [
            f"## {source.name}",
            "",
            f"- **Source:** [{source.repo}](https://github.com/{source.repo})",
            f"- **Commit:** `{source.commit}`",
            f"- **Licence:** {source.licence}",
            f"- **Files:** {counts.get(source.name, 0)}",
            "",
            source.why,
            "",
        ]
    return "\n".join(lines)


if __name__ == "__main__":
    main()
